# fly.toml app configuration file generated for zen-demo-nodejs-esm on 2025-09-17T19:10:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zen-demo-nodejs-esm'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile-esm'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2048mb'
  cpu_kind = 'performance'
  cpus = 1
