# fly.toml app configuration file generated for sovulnerable on 2024-09-17T17:42:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sovulnerable'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.http_options.response.headers]
    Server = "Apache/2.4.6 (CentOS) PHP/5.4.16"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
